### ISSUE TITLE
Where is the UserChrome.css posted on uniporn?

### ISSUE THREAD

**Issue by sk0x1234** [jujey/dots#1]

**Comment by jujey** [comment]
the userChrome.css wasn't mine, that's why it's not here, but I recently did my own userChrome.css it's smoother and cleaner imo https://github.com/jujey/dots/blob/master/openbox/chrome/userChrome.css and here's an example of how it looks like on my machine https://i.imgur.com/wM2Ro9c.png

**Comment by jujey** [comment]
better example: https://i.imgur.com/2qM2LSQ.mp4
